config/routes.rb
Rails.application.routes.draw do
  namespace :webinars do
    resources :positions
  end
  resources :webinars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/webinar.rb
class Webinar < ApplicationRecord
end

app/models/webinars.rb
module Webinars
  def self.table_name_prefix
    'webinars_'
  end
end

app/models/webinars/position.rb
class Webinars::Position < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/webinars/positions_controller.rb
class Webinars::PositionsController < ApplicationController
  before_action :set_webinars_position, only: [:show, :edit, :update, :destroy]

  # GET /webinars/positions
  # GET /webinars/positions.json
  def index
    @webinars_positions = Webinars::Position.all
  end

  # GET /webinars/positions/1
  # GET /webinars/positions/1.json
  def show
  end

  # GET /webinars/positions/new
  def new
    @webinars_position = Webinars::Position.new
  end

  # GET /webinars/positions/1/edit
  def edit
  end

  # POST /webinars/positions
  # POST /webinars/positions.json
  def create
    @webinars_position = Webinars::Position.new(webinars_position_params)

    respond_to do |format|
      if @webinars_position.save
        format.html { redirect_to @webinars_position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @webinars_position }
      else
        format.html { render :new }
        format.json { render json: @webinars_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webinars/positions/1
  # PATCH/PUT /webinars/positions/1.json
  def update
    respond_to do |format|
      if @webinars_position.update(webinars_position_params)
        format.html { redirect_to @webinars_position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @webinars_position }
      else
        format.html { render :edit }
        format.json { render json: @webinars_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinars/positions/1
  # DELETE /webinars/positions/1.json
  def destroy
    @webinars_position.destroy
    respond_to do |format|
      format.html { redirect_to webinars_positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webinars_position
      @webinars_position = Webinars::Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webinars_position_params
      params.require(:webinars_position).permit(:name)
    end
end

app/controllers/webinars_controller.rb
class WebinarsController < ApplicationController
  before_action :set_webinar, only: [:show, :edit, :update, :destroy]

  # GET /webinars
  # GET /webinars.json
  def index
    @webinars = Webinar.all
  end

  # GET /webinars/1
  # GET /webinars/1.json
  def show
  end

  # GET /webinars/new
  def new
    @webinar = Webinar.new
  end

  # GET /webinars/1/edit
  def edit
  end

  # POST /webinars
  # POST /webinars.json
  def create
    @webinar = Webinar.new(webinar_params)

    respond_to do |format|
      if @webinar.save
        format.html { redirect_to @webinar, notice: 'Webinar was successfully created.' }
        format.json { render :show, status: :created, location: @webinar }
      else
        format.html { render :new }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webinars/1
  # PATCH/PUT /webinars/1.json
  def update
    respond_to do |format|
      if @webinar.update(webinar_params)
        format.html { redirect_to @webinar, notice: 'Webinar was successfully updated.' }
        format.json { render :show, status: :ok, location: @webinar }
      else
        format.html { render :edit }
        format.json { render json: @webinar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webinars/1
  # DELETE /webinars/1.json
  def destroy
    @webinar.destroy
    respond_to do |format|
      format.html { redirect_to webinars_url, notice: 'Webinar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webinar
      @webinar = Webinar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webinar_params
      params.require(:webinar).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webinars/positions_helper.rb
module Webinars::PositionsHelper
end

app/helpers/webinars_helper.rb
module WebinarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Namespacer2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/webinars/_form.html.erb
<%= form_with(model: webinar, local: true) do |form| %>
  <% if webinar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webinar.errors.count, "error") %> prohibited this webinar from being saved:</h2>

      <ul>
        <% webinar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webinars/edit.html.erb
<h1>Editing Webinar</h1>

<%= render 'form', webinar: @webinar %>

<%= link_to 'Show', @webinar %> |
<%= link_to 'Back', webinars_path %>

app/views/webinars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webinars</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webinars.each do |webinar| %>
      <tr>
        <td><%= webinar.title %></td>
        <td><%= link_to 'Show', webinar %></td>
        <td><%= link_to 'Edit', edit_webinar_path(webinar) %></td>
        <td><%= link_to 'Destroy', webinar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webinar', new_webinar_path %>

app/views/webinars/new.html.erb
<h1>New Webinar</h1>

<%= render 'form', webinar: @webinar %>

<%= link_to 'Back', webinars_path %>

app/views/webinars/positions/_form.html.erb
<%= form_with(model: webinars_position, local: true) do |form| %>
  <% if webinars_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webinars_position.errors.count, "error") %> prohibited this webinars_position from being saved:</h2>

      <ul>
        <% webinars_position.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webinars/positions/edit.html.erb
<h1>Editing Webinars Position</h1>

<%= render 'form', webinars_position: @webinars_position %>

<%= link_to 'Show', @webinars_position %> |
<%= link_to 'Back', webinars_positions_path %>

app/views/webinars/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webinars Positions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webinars_positions.each do |webinars_position| %>
      <tr>
        <td><%= webinars_position.name %></td>
        <td><%= link_to 'Show', webinars_position %></td>
        <td><%= link_to 'Edit', edit_webinars_position_path(webinars_position) %></td>
        <td><%= link_to 'Destroy', webinars_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webinars Position', new_webinars_position_path %>

app/views/webinars/positions/new.html.erb
<h1>New Webinars Position</h1>

<%= render 'form', webinars_position: @webinars_position %>

<%= link_to 'Back', webinars_positions_path %>

app/views/webinars/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @webinars_position.name %>
</p>

<%= link_to 'Edit', edit_webinars_position_path(@webinars_position) %> |
<%= link_to 'Back', webinars_positions_path %>

app/views/webinars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @webinar.title %>
</p>

<%= link_to 'Edit', edit_webinar_path(@webinar) %> |
<%= link_to 'Back', webinars_path %>